export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_STYLES = 'GET_STYLES';
export const ERROR = 'ERROR';
export const CHANGE_STYLE = 'CHANGE_STYLE';
export const CHANGE_PRODUCT = 'CHANGE_PRODUCT';
export const GET_PRODUCT_STYLES = 'GET_PRODUCT_STYLES';
export const GET_PRODUCT_META = 'GET_PRODUCT_META';